### ISSUE TITLE
Ubuntu 20.04.1安装pynvme失败

### ISSUE THREAD

**Issue by yxjhy001** [pynvme/pynvme#118]
CC module/bdev/lvol/vbdev_lvol.o
  CC module/bdev/error/vbdev_error.o
  CC module/bdev/null/bdev_null.o
  CC module/bdev/nvme/bdev_nvme.o
  CC module/bdev/gpt/vbdev_gpt.o
  CC module/blobfs/bdev/blobfs_bdev_rpc.o
  CC module/bdev/error/vbdev_error_rpc.o
  CC module/bdev/null/bdev_null_rpc.o
  CC module/bdev/malloc/bdev_malloc_rpc.o

make[1]: Entering directory '/root/yxj/pynvme/src'
  CC src/driver.o
  CC src/intr_mgt.o
  CC src/ioworker.o
  LIB libspdk_pynvme.a
Compiling driver_wrap.pyx because it changed.
[1/1] Cythonizing driver_wrap.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        self._timeout = _cTIMEOUT*1000
        self.nvme_init_func = nvme_init_func
        self.aer_cb_func = None

        # register timeout callback
        d.nvme_register_timeout_cb(self.pcie._ctrlr, timeout_driver_cb, self._timeout)
                                                     ^
------------------------------------------------------------

driver_wrap.pyx:900:53: Cannot assign type 'void (void *, ctrlr *, qpair *, unsigned short) except *' to 'timeout_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, ctrlr *, qpair *, unsigned short) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
        # Parameters
            msec (int): milli-seconds of timeout value
        """

        self._timeout = msec
        d.nvme_register_timeout_cb(self.pcie._ctrlr, timeout_driver_cb, self._timeout)
                                                     ^
------------------------------------------------------------

driver_wrap.pyx:1026:53: Cannot assign type 'void (void *, ctrlr *, qpair *, unsigned short) except *' to 'timeout_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, ctrlr *, qpair *, unsigned short) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=0,
                            cdw12=0,
                            cdw13=0,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1200:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=(csi << 24) | nvmsetid,
                            cdw12=0,
                            cdw13=0,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1227:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=cdw11,
                            cdw12=cdw12,
                            cdw13=cdw13,
                            cdw14=cdw14,
                            cdw15=cdw15,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1270:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=cdw11,
                            cdw12=cdw12,
                            cdw13=cdw13,
                            cdw14=cdw14,
                            cdw15=cdw15,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1298:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=(dwords>>16) & 0xffff,
                            cdw12=offset,
                            cdw13=offset >> 32,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1335:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=opcode,
                            cdw12=dword0,
                            cdw13=dword1,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1364:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=opcode,
                            cdw12=dword0,
                            cdw13=dword1,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1393:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=0,
                            cdw12=0,
                            cdw13=0,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1424:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=pattern,
                            cdw12=0,
                            cdw13=0,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1449:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=0,
                            cdw12=0,
                            cdw13=0,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1473:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=(offset>>2),  # unit is dword
                            cdw12=0,
                            cdw13=0,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1500:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=0,
                            cdw12=0,
                            cdw13=0,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1529:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=0,
                            cdw12=0,
                            cdw13=0,
                            cdw14=0,
                            cdw15=0,
                            cb_func=aer_cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1575:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=size,
                            cdw12=0,
                            cdw13=0,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1607:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11=size,
                            cdw12=0,
                            cdw13=0,
                            cdw14=0,
                            cdw15=0,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1639:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                            cdw11,
                            cdw12,
                            cdw13,
                            cdw14,
                            cdw15,
                            cb_func=cmd_cb,
                                    ^
------------------------------------------------------------

driver_wrap.pyx:1669:36: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
        """

        assert buf is not None, "no buffer allocated"

        self.send_read_write(2, qpair, buf, lba, lba_count,
                             io_flags, cmd_cb, <void*>cb,
                                       ^
------------------------------------------------------------

driver_wrap.pyx:2132:39: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
        """

        assert buf is not None, "no buffer allocated"

        self.send_read_write(1, qpair, buf, lba, lba_count,
                             io_flags, cmd_cb, <void*>cb,
                                       ^
------------------------------------------------------------

driver_wrap.pyx:2161:39: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...

        # send the command
        self.send_io_raw(qpair, buf, 9, self._nsid,
                         range_count-1, attribute,
                         0, 0, 0, 0,
                         cmd_cb, <void*>cb)
                         ^
------------------------------------------------------------

driver_wrap.pyx:2192:25: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...

        self.send_io_raw(qpair, None, 0xc, self._nsid,
                         lba&0xffffffff, lba>>32,
                         (lba_count-1)|(io_flags<<16),
                         0, 0, 0,
                         cmd_cb, <void*>cb)
                         ^
------------------------------------------------------------

driver_wrap.pyx:2216:25: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...

        self.send_io_raw(qpair, buf, 5, self._nsid,
                         lba&0xffffffff, lba>>32,
                         (lba_count-1)|(io_flags<<16),
                         0, 0, 0,
                         cmd_cb, <void*>cb)
                         ^
------------------------------------------------------------

driver_wrap.pyx:2246:25: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
            SystemError: the command fails
        """

        self.send_io_raw(qpair, None, 0, self._nsid,
                         0, 0, 0, 0, 0, 0,
                         cmd_cb, <void*>cb)
                         ^
------------------------------------------------------------

driver_wrap.pyx:2265:25: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...

        self.send_io_raw(qpair, None, 4, self._nsid,
                         lba&0xffffffff, lba>>32,
                         lba_count-1,
                         0, 0, 0,
                         cmd_cb, <void*>cb)
                         ^
------------------------------------------------------------

driver_wrap.pyx:2288:25: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...

        self.send_io_raw(qpair, None, 8, self._nsid,
                         lba&0xffffffff, lba>>32,
                         (lba_count-1)|(io_flags<<16),
                         0, 0, 0,
                         cmd_cb, <void*>cb)
                         ^
------------------------------------------------------------

driver_wrap.pyx:2312:25: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...

        self.send_io_raw(qpair, buf, 0x7a, self._nsid,
                         slba&0xffffffff, slba>>32,
                         dwords-1,
                         (partial<<16)+(state<<8)+extended, 0, 0,
                         cmd_cb, <void*>cb)
                         ^
------------------------------------------------------------

driver_wrap.pyx:2353:25: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
    def zns_mgmt_send(self, qpair, buf, slba=0, action=0, all=False, cb=None):
        self.send_io_raw(qpair, buf, 0x79, self._nsid,
                         slba&0xffffffff, slba>>32,
                         0,
                         (all<<8)+action, 0, 0,
                         cmd_cb, <void*>cb)
                         ^
------------------------------------------------------------

driver_wrap.pyx:2361:25: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
                         cdw11,
                         cdw12,
                         cdw13,
                         cdw14,
                         cdw15,
                         cb_func=cmd_cb,
                                 ^
------------------------------------------------------------

driver_wrap.pyx:2392:33: Cannot assign type 'void (void *, const cpl *) except *' to 'cmd_cb_func'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, const cpl *) except *'.
Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    '../spdk/dpdk/build/lib/librte_kvargs.a',
  File "/usr/local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: driver_wrap.pyx
make[1]: *** [Makefile:52: cython_lib] Error 1
make[1]: Leaving directory '/root/yxj/pynvme/src'
make: *** [Makefile:46: all] Error 2
sudo sh -c "echo 1 > /sys/bus/pci/rescan"
sudo rm -rf /run/dpdk
sudo rm -rf /var/run/dpdk
sudo ./src/setup.sh cleanup
ls: cannot access '/dev/shm/*': No such file or directory
Clean
sudo ./src/setup.sh reset
0000:01:00.0 (1ded 5236): Already using the nvme driver
sudo rm -f /var/tmp/spdk.sock*
sudo rm -f /var/tmp/pynvme.sock*
sudo rm -rf .pytest_cache
sudo fuser -k 4420/tcp
make: [Makefile:73: reset] Error 1 (ignored)
sudo sh -c 'find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf'
xhost +local:           # enable GUI with root/sudo
xhost:  unable to open display ""
make: [Makefile:93: setup] Error 1 (ignored)
sudo chmod 777 /tmp
sudo sh -c 'find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf'
sed -i 's/XXXX:BB:DD.F/0000:01:00.0/g' .vscode/settings.json
sudo HUGEMEM=2430    DRIVER_OVERRIDE=uio_pci_generic ./src/setup.sh     # UIO is recommended
0000:01:00.0 (1ded 5236): nvme -> uio_pci_generic
rm test_0000:01:00.0.log
rm: cannot remove 'test_0000:01:00.0.log': No such file or directory
make: [Makefile:111: test] Error 1 (ignored)
make pytest 2>test_0000:01:00.0.log | tee -a test_0000:01:00.0.log
make[1]: Entering directory '/root/yxj/pynvme'

root@alibaba-System-Product-Name:~/yxj/pynvme# make setup
sudo sh -c "echo 1 > /sys/bus/pci/rescan"
sudo rm -rf /run/dpdk
sudo rm -rf /var/run/dpdk
sudo ./src/setup.sh cleanup
ls: cannot access '/dev/shm/*': No such file or directory
Clean
sudo ./src/setup.sh reset
0000:01:00.0 (1ded 5236): uio_pci_generic -> nvme
sudo rm -f /var/tmp/spdk.sock*
sudo rm -f /var/tmp/pynvme.sock*
sudo rm -rf .pytest_cache
sudo fuser -k 4420/tcp
make: [Makefile:73: reset] Error 1 (ignored)
sudo sh -c 'find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf'
xhost +local:           # enable GUI with root/sudo
xhost:  unable to open display ""
make: [Makefile:93: setup] Error 1 (ignored)
sudo chmod 777 /tmp
sudo sh -c 'find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf'
sed -i 's/XXXX:BB:DD.F/0000:01:00.0/g' .vscode/settings.json
sudo HUGEMEM=2430    DRIVER_OVERRIDE=uio_pci_generic ./src/setup.sh     # UIO is recommended
0000:01:00.0 (1ded 5236): nvme -> uio_pci_generic

**Comment by Harish888-404** [comment]
Could you please let me know how to fix this issue? I'm on the same ubuntu version

**Comment by Gracecao199312** [comment]
it seems your python lib cython is not matched, assignment other cython version is a smart way:pip3 install Cython==3.0.0a10
